import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/header'
import NavBar from '../components/Navbar'
import Results from '../components/Results'
import requests from '../utils/requests'

export default function Home({ data }) {
  console.log(data)
  return (
    <div>
      <Head>
        <title>Hulu 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Header */}
      <Header />

      {/* NavBar */}
      <NavBar />

      {/* Results */}
      <Results results={data} />
    </div>
  )
}



export const getServerSideProps = async (context) => {
  const genre = context.query.genre
  const request = await fetch(`https://api.themoviedb.org/3${requests[genre]?.url || requests.fetchTrending.url}`)
  const data = await request.json()

  return {
    props: {
      data: data.results
    }
  }
}